CRITICAL - 2022-02-22 17:18:14 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\code\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\code\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\code\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\code\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-02-22 17:18:41 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\code\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\code\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\code\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\code\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-02-22 17:18:55 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\code\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\code\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\code\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\code\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-02-22 17:24:51 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\code\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\code\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\code\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\code\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-02-22 17:25:03 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\code\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\code\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\code\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\code\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-02-22 17:25:05 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\code\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\code\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\code\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\code\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-02-22 10:36:13 --> include(db_connect.php): failed to open stream: No such file or directory
#0 C:\xampp\htdocs\code\app\Views\Front\Home.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(db_conn...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\code\app\Views\Front\Home.php(27): include()
#2 C:\xampp\htdocs\code\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\code\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\code\system\Common.php(1089): CodeIgniter\View\View->render('Front/Home', Array, true)
#5 C:\xampp\htdocs\code\app\Controllers\Front\Home.php(10): view('Front/Home')
#6 C:\xampp\htdocs\code\system\CodeIgniter.php(825): App\Controllers\Front\Home->index()
#7 C:\xampp\htdocs\code\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front\Home))
#8 C:\xampp\htdocs\code\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-22 10:36:44 --> syntax error, unexpected '.'
#0 C:\xampp\htdocs\code\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\code\system\Common.php(1089): CodeIgniter\View\View->render('Front/Home', Array, true)
#2 C:\xampp\htdocs\code\app\Controllers\Front\Home.php(10): view('Front/Home')
#3 C:\xampp\htdocs\code\system\CodeIgniter.php(825): App\Controllers\Front\Home->index()
#4 C:\xampp\htdocs\code\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front\Home))
#5 C:\xampp\htdocs\code\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-22 10:36:55 --> include(db_connect.php): failed to open stream: No such file or directory
#0 C:\xampp\htdocs\code\app\Views\Front\Home.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(db_conn...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\code\app\Views\Front\Home.php(27): include()
#2 C:\xampp\htdocs\code\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\code\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\code\system\Common.php(1089): CodeIgniter\View\View->render('Front/Home', Array, true)
#5 C:\xampp\htdocs\code\app\Controllers\Front\Home.php(10): view('Front/Home')
#6 C:\xampp\htdocs\code\system\CodeIgniter.php(825): App\Controllers\Front\Home->index()
#7 C:\xampp\htdocs\code\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Front\Home))
#8 C:\xampp\htdocs\code\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-22 21:35:47 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:35:47 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:35:50 --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 439, Array)
#1 C:\xampp\htdocs\code\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 C:\xampp\htdocs\code\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\code\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\code\system\CodeIgniter.php(302): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-22 21:35:50 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:35:50 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:35:50 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:36:18 --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 439, Array)
#1 C:\xampp\htdocs\code\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 C:\xampp\htdocs\code\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\code\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\code\system\CodeIgniter.php(302): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-22 21:36:18 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:36:18 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:36:18 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:37:28 --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 439, Array)
#1 C:\xampp\htdocs\code\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 C:\xampp\htdocs\code\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\code\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\code\system\CodeIgniter.php(302): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-22 21:37:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:37:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:37:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:38:57 --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 439, Array)
#1 C:\xampp\htdocs\code\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 C:\xampp\htdocs\code\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\code\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\code\system\CodeIgniter.php(302): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-22 21:38:57 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:38:57 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:38:57 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:39:42 --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 439, Array)
#1 C:\xampp\htdocs\code\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 C:\xampp\htdocs\code\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\code\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\code\system\CodeIgniter.php(302): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\code\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-22 21:39:42 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:39:44 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-22 21:39:44 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\code\app\Config\Events.php:32) in C:\xampp\htdocs\code\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 112, Array)
#1 C:\xampp\htdocs\code\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
